# Generated by Django 5.1.4 on 2025-01-05 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='file_data',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
